FROM node:20-alpine

WORKDIR /usr/app/metaverse

COPY ./package*.json ./
COPY ./packages ./packages
COPY ./turbo.json ./
RUN npm install
COPY ./apps/frontend ./apps/frontend


WORKDIR /usr/app/metaverse/apps/frontend

CMD ["npm", "run", "dev"]
