

FROM node:18-alpine

WORKDIR /usr/app/metaverse

# RUN npm install -g pnpm

COPY ./package*.json ./
COPY ./turbo.json ./
# COPY ./pnpm-*.yaml ./
COPY ./apps/http ./apps/http
COPY ./packages ./packages

RUN npm install
RUN npm install -g nodemon


# RUN pnpm run build

EXPOSE 3000

CMD [ "npm", "run", "start:http" ]